CREATE TABLE talhoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propriedade_id BIGINT NOT NULL,
    nome VARCHAR(80) NOT NULL,
    area_hectares DOUBLE PRECISION NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_talhoes_propriedade FOREIGN KEY (propriedade_id) REFERENCES propriedades_rurais (id)
);